[package]
name = "rust_parse_csv"
version = "0.1.0"
edition = "2021"

[dependencies]
extism-pdk = "1.0"
csv = "1.3"
serde_json = "1.0"
protobuf = "3.3"

[build-dependencies]
protobuf-codegen = "3.3"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true
strip = true